config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  devise_for :users, skip: [:registrations, :passwords], :controllers => {
      :sessions         => 'users/sessions',
      :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  get '/users/auth/failure', to: 'users#index'

  #[参考]https://stackoverflow.com/questions/22887765/rails-route-only-if-resource-is-present
  constraints(lambda {|req| User.exists?(nickname:req.params[:nickname])}) do
    scope '(:nickname)' do
      resources :summaries, except: [:edit, :destroy] do
        resources :contents, only: [:new,:create]
      end

      #deleteだけ別にして名前をつけるようにした。
      delete '/summaries/:id', to: 'summaries#destroy', as: :delete_summary
      delete '/summaries/:summary_id/contents/:id', to: 'contents#destroy', as: :delete_summary_content

      get '', to: 'users#show',           as: :user_info
      get '/others_summaries', to: 'users#show',   as: :user_others_summaries
      get '/profile', to: 'users#profile',as: :user_profile

      get '/contents', to: 'contents#index'
      delete '/contents/:id', to: 'contents#destroy', as: :delete_content
    end
  end

end

app/models/summary.rb
## update_annotate
## update_annotate
## update_annotate

class Summary < ApplicationRecord
  belongs_to :user
  has_many :contents, dependent: :destroy
  accepts_nested_attributes_for :contents

  validates :title, :presence => true

end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  before_action :set_summary, only: [:show, :edit, :update, :destroy]
  before_action :build_summary, only: :create
  before_action :you_look_user

  include GrapeSlack::SlackUrlProccesable

  def index
    @summaries = you_look_user.summaries.page(params[:page])
  end

  def show
    @contents = @summary.contents.page(params[:page])
  end

  def new
    @summary = Summary.new
    @summary.contents.build
    #一旦redisに保存してたキーを削除して再度作成
    SlackMemberJob.perform_later
    SlackChannelListJob.perform_later
  end

  def create
    if @summary.save
      redirect_to summaries_path(current_user.nickname), notice: I18n.t('user.summaries.messages.create')
    else
      @summary = current_user.summaries.build(summary_params)
      @summary.validate
      render :new
    end
  end

  def update
    if @summary.update(summary_params)
      redirect_to @summary, notice: I18n.t('user.summaries.messages.update')
    else
      render :edit
    end
  end

  def destroy
    @summary.destroy
    redirect_to summaries_path(current_user.nickname), notice: I18n.t('user.summaries.messages.destroy')
  end

  private

  def set_summary
    #TODO: summary_paramsで通すように書き直す
    @summary = Summary.where(user_id: you_look_user.id).find_by(id:params[:id])
  end

  def only_summary_params
    params.require(:summary).permit(
                                :title, :user_id
    )
  end

  def summary_params
    params.require(:summary).permit(
        :title, :user_id,
        contents_attributes:[:id, :slack_url]
    )
  end

  def build_summary
    @summary = current_user.summaries.build(only_summary_params)
    txt_slack_urls = summary_params['contents_attributes']['0']['slack_url']
    @summary.contents.build(contents_params_after_treatment(txt_slack_urls))
  end

end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/views/summaries/_form.html.erb
<%= form_for summary, :url => url_for(:controller => 'summaries',
                                      :action => 'create',
                                      :nickname => current_user.nickname) do |f| %>

    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key.to_s.split('_').first %>">
          <%= value %>
        </div>
    <% end %>

    <% if summary.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(summary.errors.count, "error") %> prohibited this summary from being saved:</h2>

          <ul>
            <% summary.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label t('user.summaries.forms.title') %>
      <%= f.text_field :title, {:class => 'form-control'} %>
    </div>

    <div class="form-group">
      <%= f.fields_for :contents do |f_contents| %>
          <%= f_contents.label t('user.summaries.forms.url', kind: 'Slack') %>
          <%= f_contents.text_area :slack_url, {:class => 'form-control', :rows => 10} %>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit :class => 'btn btn-primary btn-sm' %>
      <%= link_to t('user.summaries.forms.cancel'), summaries_path(current_user.nickname) %>
    </div>

<% end %>

app/views/summaries/index.html.erb
<div class="col-md-10">
  <h3><strong>
    <% if you_look_user.nickname != current_user.nickname %>
        <%= "#{you_look_user.name}さんの" %>
    <% end %>
    <%= t('user.summaries.title') %></strong></h3>
</div>
<div class="col-md-2" style="margin-left:auto;">
  <% if you_look_user.nickname == current_user.nickname %>
      <div style="text-align:right;">
        <%= link_to t('user.summaries.forms.create'), new_summary_path(current_user.nickname), {
            :class => 'btn btn-sm btn-primary',
            :style => 'color:white;'} %>
      </div>
  <% end %>
</div>

<% if @summaries.count != 0 %>
    <table class="table table-striped table-responsive table-hover summaries">
      <thead>
      <tr>
        <th><%= t('user.summaries.tables.row_1_title') %></th>
        <th><%= t('user.summaries.tables.row_2_count') %></th>
        <% if you_look_user.nickname == current_user.nickname %>
            <th colspan="2"></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <% @summaries.each do |summary| %>
          <tr>
            <td><%= link_to summary.title, summary_path(you_look_user.nickname, summary.id) %></td>
            <td><%= summary.contents.size %></td>
            <% if you_look_user.nickname == current_user.nickname %>
                <td><%= link_to t('commons.add'), new_summary_content_path(current_user.nickname, summary.id), {
                    :class => 'btn btn-info btn-sm'
                } %></td>
                <td><%= link_to t('commons.delete'),
                                delete_summary_path(current_user.nickname,summary.id),
                                {
                                    :method => :delete,
                                    :class  => 'btn btn-danger btn-sm',
                                    :style  => 'color:white;',
                                    :data   => {confirm: t('commons.are_you_sure')}
                                }
                %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @summaries %>
<% end %>

app/views/summaries/new.html.erb
<h3><strong><%= t('user.summaries.tables.create') %></strong></h3>
<%= render :partial => 'form', locals: { summary: @summary} %>

app/views/summaries/show.html.erb
<h3><strong><%= @summary.title %></strong></h3>
<br>
<% @contents.each do |content| %>
    <ul class="list-unstyled">
      <li class="media">
        <div class="media-left">
          <%= image_tag(content.profile_image_48_url, {
              :class => 'd-flex align-self-start mr-3',
              :size  => '48x48',
              :alt   => 'Generic placeholder image'}) %>
        </div>
        <div class="media-body">
          <h5 class="media-title mt-0 mb-1"><strong><%= content.name %></strong></h5>
          <p style="word-wrap:break-word;"><%= content.slack_message %></p>
        </div>
        <% if you_look_user.nickname == current_user.nickname %>
            <div class="media-right">
              <%= link_to t('commons.delete'), delete_summary_content_path(current_user.nickname,@summary.id,content.id), {
                  :class => 'btn btn-danger btn-sm',
                  :style => 'color:white;',
                  :method => :delete,
                  :data => { confirm: t('commons.are_you_sure') }
              } %>
            </div>
        <% end %>
      </li>
      <hr>
    </ul>
<% end %>
<%= paginate @contents %>

<div class="actions">
  <%= link_to t('user.summaries.forms.back'), summaries_path(you_look_user.nickname), {
      :class => 'btn btn-sm btn-primary',
      :style => 'color:white;'
       } %>
</div>