config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  devise_for :users, skip: [:registrations, :passwords], :controllers => {
      :sessions         => 'users/sessions',
      :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  get '/users/auth/failure', to: 'users#index'

  #[参考]https://stackoverflow.com/questions/22887765/rails-route-only-if-resource-is-present
  constraints(lambda {|req| User.exists?(nickname:req.params[:nickname])}) do
    scope '(:nickname)' do
      resources :summaries, except: [:edit, :destroy] do
        resources :contents, only: [:new,:create]
      end

      #deleteだけ別にして名前をつけるようにした。
      delete '/summaries/:id', to: 'summaries#destroy', as: :delete_summary
      delete '/summaries/:summary_id/contents/:id', to: 'contents#destroy', as: :delete_summary_content

      get '', to: 'users#show',           as: :user_info
      get '/others_summaries', to: 'users#show',   as: :user_others_summaries
      get '/profile', to: 'users#profile',as: :user_profile

      get '/contents', to: 'contents#index'
      delete '/contents/:id', to: 'contents#destroy', as: :delete_content
    end
  end

end

app/views/shared/_content.html.erb
<div class="container-fluid content">
  <%= render :partial => 'shared/flash' %>
  <%= yield %>
</div>

app/views/shared/_flash.html.erb
<div class="flash">
  <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
  <% end %>
  <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<% unless current_page?(root_path) or current_page?(users_auth_failure_path) %>

    <div class="container-fluid" style="background-color:purple;">

        <strong class="navbar-brand text-muted" style="text:bold;color:white;text-align:left;">GrapeSlack</strong>

      <ul class="nav navbar-nav navbar-right">

        <li>
          <%= link_to(user_profile_path(current_user.nickname), {
              :class => 'text-muted',
              :style => 'color:white;'
          }) do %>
              <strong><%= "#{current_user.name}さん" %></strong>
          <% end %>
        </li>

        <li>
          <%= link_to t('commons.logout'), destroy_user_session_path, {
              :method => :delete,
              :style => 'text-align:right;color:white;margin-right:10px;'
          } %>
        </li>
      </ul>

    </div>
<% end %>

app/views/shared/_sidemenu.html.erb
<div class="container-fluid">
  <div id="sidebar-wrapper" class="sidebar-toggle">
    <ul class="sidebar-nav">
      <li><%= link_to t('user.profile.title'), user_profile_path(current_user.nickname) %></li>
      <li><%= link_to t('user.others_summaries.title'), user_others_summaries_path(current_user.nickname) %></li>
      <li><%= link_to t('user.summaries.title'), summaries_path(current_user.nickname) %></li>
      <li><%= link_to t('user.contents.title'), contents_path(current_user.nickname) %></li>
    </ul>
  </div>
</div>

app/views/shared/base.html.erb
<% unless current_page?(root_path) || current_page?(users_auth_failure_path) %>

    <div class="container-fluid main">
      <div class="col-md-3">
        <%= render :partial => 'shared/sidemenu' %>
      </div>
      <div class="col-md-9" style="border: 1px solid purple;">
        <%= render :partial => 'shared/content' %>
      </div>
    </div>

<% else %>
    <%= yield %>
<% end %>